settings:
    # Possible server types: 'daemon', 'frontend'
    # When running frontend, a daemon will also run
    server_type: 'frontend'
    daemon:
        port: 3137
        host: "0.0.0.0"
    frontend:
        port: 8080
        # Frontend authentication. If true, it will authenticate all connected users to the panel with the given username / password.
        # Username and password combinations are located in ~/users.htpasswd
        auth: false
# This is not necessary if you are only running a daemon off this machine.
servers:
    # Example server
    1:
        name: "localhost"
        host: "127.0.0.1"
        port: "3137"
        id: 1
